---
title: "AE-Bayes"
author: "Your Name Here"
format: 
  html:
    self-contained: true
    toc: true
    toc_float: true
    number_section: false
    highlight: "tango"
    theme: "cosmo"
    df-print: paged
editor: visual
editor_options: 
  chunk_output_type: console
---

This Application Exercise walks through examples from the [Bayes Rules! textbook](https://www.bayesrulesbook.com). There are spaces for you to answer each question (with code and/or text). Feel free to also use this document to add your own notes along the way.

## Load packages & data

```{r}
#| label: load-packages-data
#| message: false
#| warning: false

# Load packages
library(bayesrules)
library(tidyverse)
library(janitor)
library(cowplot)
```

```{r}
#optimist prior - beta(14,1)
p1 <- plot_beta(alpha = 14, beta = 1)
summarize_beta(alpha = 14, beta = 1)

#clueless prior - beta(1,1)


#pessimist prior - beta(5,11)


#import bechdel dataset
data(bechdel)

#set seed and take random sample
set.seed(84735)


#compute summary statistics


#summarize posterior - optimist
summarize_beta_binomial(alpha = 14, beta = 1, y = y, n = n)
plot_beta_binomial(alpha = 14, beta = 1, y = y, n = n)

#summarize posterior - clueless


#summarize posterior - pessimist

```

```{r}
#same prior, different data

#oksana - 1991


#omari - 2000


#orlando - 2013
```
